/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcprog.h"

bool_t
xdr_send_data (XDR *xdrs, send_data *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_receive_data (XDR *xdrs, receive_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->double_arr.double_arr_val, (u_int *) &objp->double_arr.double_arr_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->int_arr.int_arr_val, (u_int *) &objp->int_arr.int_arr_len, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
